import React from 'react';

interface GeneratedImageProps {
    isLoading: boolean;
    error: string | null;
    imageUrl: string | null;
}

export const GeneratedImage: React.FC<GeneratedImageProps> = ({ isLoading, error, imageUrl }) => {
    if (!isLoading && !error && !imageUrl) {
        return null; // Don't render anything initially
    }

    return (
        <div className="mb-12 aspect-square w-full max-w-xl mx-auto bg-brand-dark-light rounded-lg flex items-center justify-center p-4 border border-brand-gray/50">
            {isLoading && (
                <div className="text-center">
                    <div className="w-16 h-16 border-4 border-dashed rounded-full animate-spin border-brand-purple-light mx-auto"></div>
                    <p className="text-gray-300 mt-4">Generating your masterpiece...</p>
                    <p className="text-sm text-gray-500">This can take a few moments.</p>
                </div>
            )}
            {error && (
                <div className="text-center text-red-400">
                    <p className="font-bold">An Error Occurred</p>
                    <p>{error}</p>
                </div>
            )}
            {imageUrl && !isLoading && (
                 <img src={imageUrl} alt="Generated by AI" className="rounded-lg shadow-2xl object-contain max-h-full max-w-full" />
            )}
        </div>
    );
};
